### ISSUE TITLE
Web browser gamee mode is not running as expected in Metal Ulefone

### ISSUE THREAD

**Issue by WyRe** [gameeapp/gamee-js#18]
Hi guys, like I've said in my last comment https://github.com/gameeapp/gamee-js/issues/17#issuecomment-353914201 I'm experiencing issues when I try to play in my device from most widely used browsers, however Gamee app for android works pretty fine. I've considered more appropiated to open a new issue, due you seem are developing the Gamee app among other related things. You can found info about my device in [their website](http://ulefone.com/products/metal/features.html) and in [official forum](http://forum.ulefone.com/forum-68-1.html). I'm running a [cooked ROM](https://forum.xda-developers.com/android/development/rom-unofficial-aosp-n-ulefone-metal-t3521714), here are the details:

![romulefoneinfo](https://user-images.githubusercontent.com/4059108/34361288-ee0cdc32-ea68-11e7-99db-784845b22fb5.gif)

I've created several gifs showing the specific issue: 

First, the Telegram web browser:

![atomicdrumpissue1](https://user-images.githubusercontent.com/4059108/34360940-f28a745c-ea65-11e7-99a8-6a1599c28539.gif)

Second Chrome Beta browser: 

![atomicdrumpissue2](https://user-images.githubusercontent.com/4059108/34361167-11bb4142-ea68-11e7-8791-316f35e1ca90.gif)

Finally the Gamee app for android (working as is expected):

![atomicdrumpissue3](https://user-images.githubusercontent.com/4059108/34361305-2c62f796-ea69-11e7-9c2c-1fba1204c742.gif)

I've got exactly the same issue with Skoda Hockey, btw. This wouldn't be a major issue if I could connect the app with my Telegram groups, I think.

Sorry if this is not the appropriate site to post this kind of issues, thank you for your attention and nice social gaming!

**Comment by EntityB** [comment]
Hey @WyRe ,
yes this is the place for game developers for GAMEE. 

Anyway I examinated the problem. Thanks for the detailed report. The core thing for any game functionality is what browser core (specifically webview) is being used. Each application running our games is choosing the webview and in case of applications outside GAMEE (telegram, kik, messenger etc.) we have no control over it. 

> First, the Telegram web browser
I think Telegram installed on your device is using old webview with some kind of bug, probably render buffers issue. Telegram is using more then one webview, it is device dependent. We can only report this to Telegram. 

> Second Chrome Beta browser
Clearly a performance issue. This might be connected to "beta" browser or cooked ROM. I see even the table after the game is slow, it seems hardware acceleration might be disabled for this browser build. Or worse hardware acceleration might be disabled because of cooked ROM or implemented drivers are not complete. So my best advice is to not to use beta browser and if it doesn't help the problem is somewhere deeper. 

If you have any other info, you can post it here.

**Comment by WyRe** [comment]
> We can only report this to Telegram

Ok, but in Github just there is a Telegram Desktop code, not Android app, where should I report then? 

> This might be connected to "beta" browser or cooked ROM

I think could be more related with ROM, may be I could try [this new one](https://forum.xda-developers.com/android/development/rom-official-mados-ulefone-metal-t3709342) because the error also happens in stable Chrome. Could I check the hardware acceleration in Chrome app?
